### ISSUE TITLE
Zigbee2MQTT Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

### ISSUE THREAD

**Issue by batamire** [SensorsIot/IOTstack#306]
A beginner with IOTStack and docker based HA here...

Running on PI4 4GB RAM, zigbee2mqtt log gives me:

```
Zigbee2MQTT:error 2021-04-01 16:27:22: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

When booting CC2531 lights up green but then turns off at some point.

```
pi@raspberrypi:~/IOTstack $ ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Apr  1 18:14 usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B001CD4B213-if00 -> ../../ttyACM0
```

Zigbee2MqttAssistant logs:

```
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
Unable to connect to MQTT server mosquitto.
```

And a bonus question, why is my volumes/* owned by root?

```
pi@raspberrypi:~/IOTstack $ ls -la volumes/
total 40
drwxr-xr-x 10 pi   pi   4096 Apr  1 18:22 .
drwxr-xr-x 13 pi   pi   4096 Apr  1 18:21 ..
drwxr-xr-x  4 root root 4096 Apr  1 18:22 grafana
drwxr-xr-x  7 root root 4096 Apr  1 18:32 home_assistant
drwxr-xr-x  3 root root 4096 Apr  1 18:22 influxdb
drwxr-xr-x  5 pi   pi   4096 Apr  1 18:21 mosquitto
drwxr-xr-x  3 root root 4096 Apr  1 18:22 nodered
drwxr-xr-x  3 root root 4096 Apr  1 18:22 portainer-ce
drwxr-xr-x  3 root root 4096 Apr  1 18:22 postgres
drwxr-xr-x  3 root root 4096 Apr  1 18:22 zigbee2mqtt
```

I wish getting started guide included setting up CC2531 with zigbee2mqtt as this is the most common use case 😬

**Comment by batamire** [comment]
As we are all smarter tomorrow than we were yesterday i got it running by changing `zigbee2mqtt` service in `docker-compose.yml`:

```
    devices:
    - /dev/ttyACM0:/dev/ttyACM0
    #- /dev/ttyAMA0:/dev/ttyACM0
    #- /dev/ttyUSB0:/dev/ttyACM0 # Electrolama zig-a-zig-ah! (zzh!) maybe other as well
```

The same thing I did yesterday without success. Reinstalled everything today, made this change and the light is green! ;)
