### ISSUE TITLE
The Postgres Template Throws an Error

### ISSUE THREAD

**Issue by hughk** [SensorsIot/IOTstack#464]
Attempting to create a Postgres container on the stack will throw an error on a missing file passwords.py. I have copied the version from mariaDb changing the variable names to postgresDb. This goes further but throws an error on missing generateRandomString during the build. This in turn was solved by adding generateRandomString to _from deps.common.functions_ import in build.py. The stack build now appears to work. If this works and is stable, I'll raise a PR or someone else can do the changes as they are minor.

Edit: It didn't work. The Postgres image still fails to start.

**Comment by Paraphraser** [comment]
I just tried this to see if I could replicate your experience. I'm afraid I can't. For me, it just works "out of the box".

This is what I did:

1. Clean clone of IOTstack.
2. Run the menu.
3. Choose Build Stack.
4. Choose PostGreSQL as the only container. My exact sequence was:

	- Use the down-arrow key to put the cursor on top of PostGreSQL
	- hit the space bar to select it
	- press <kbd>return</kbd> to signal my choices were complete (which goes back to the main menu).

5. Hit <kbd>esc</kbd> to exit the menu.
6. List the resulting docker-compose.yml.
7. UP the stack (an alias for `docker-compose up -d`).
8. DPS (an alias for `docker ps`) to make sure the container was running and not restarting.
9. Examine the log.

Things to note:

1. `POSTGRES_PASSWORD=IOtSt4ckpostgresDbPw` so the Python script has replaced the `%randomPassword%` placeholder.
2. The "database system is ready to accept connections" message at the end of the log.

Looks OK to me. I think there must be some other explanation for what is happening on your system.

```
pi@sec-dev:~$ git clone https://github.com/SensorsIot/IOTstack.git IOTstack
Cloning into 'IOTstack'...
remote: Enumerating objects: 7449, done.
remote: Counting objects: 100% (2188/2188), done.
remote: Compressing objects: 100% (1063/1063), done.
remote: Total 7449 (delta 1280), reused 1835 (delta 1035), pack-reused 5261
Receiving objects: 100% (7449/7449), 7.38 MiB | 10.18 MiB/s, done.
Resolving deltas: 100% (4432/4432), done.
pi@sec-dev:~$ cd IOTstack
pi@sec-dev:~/IOTstack$ ./menu.sh 

[ ... choose PostgreSQL ... ]

pi@sec-dev:~/IOTstack$ cat docker-compose.yml 
version: '3.6'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
    - POSTGRES_USER=postuser
    - POSTGRES_PASSWORD=IOtSt4ckpostgresDbPw
    - POSTGRES_DB=postdb
    ports:
    - "5432:5432"
    volumes:
    - ./volumes/postgres/data:/var/lib/postgresql/data
    networks:
    - iotstack_nw
networks:
  iotstack_nw: # Exposed by your host.
    # external: true
    name: IOTstack_Net
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.77.60.0/24
        # - gateway: 10.77.60.1

  iotstack_nw_internal: # For interservice communication. No access to outside
    name: IOTstack_Net_Internal
    driver: bridge
    internal: true
    ipam:
      driver: default
      config:
      - subnet: 10.77.76.0/24
        # - gateway: 10.77.76.1
  vpn_nw: # Network specifically for VPN
    name: IOTstack_VPN
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.77.88.0/24
        # - gateway: 192.18.200.1

  nextcloud_internal: # Network for NextCloud service
    name: IOTstack_NextCloud
    driver: bridge
    internal: true

  # default:
  #   external: true
  #   name: iotstack_nw

  # hosts_nw:
  #   driver: hosts

pi@sec-dev:~/IOTstack$ UP
[+] Running 14/14
 ⠿ postgres Pulled                                                                                                                                                                28.9s
   ⠿ ba82a1312e1e Pull complete                                                                                                                                                    8.7s
   ⠿ 4b9b8f46749c Pull complete                                                                                                                                                    9.3s
   ⠿ 79be40cc7b21 Pull complete                                                                                                                                                    9.6s
   ⠿ 58083aacce1f Pull complete                                                                                                                                                    9.9s
   ⠿ 3982b94e8bc0 Pull complete                                                                                                                                                   11.6s
   ⠿ bf9f4114aa49 Pull complete                                                                                                                                                   11.9s
   ⠿ 6f774e19c3df Pull complete                                                                                                                                                   12.1s
   ⠿ d04265906b16 Pull complete                                                                                                                                                   12.3s
   ⠿ c4d8beccb551 Pull complete                                                                                                                                                   23.5s
   ⠿ fc8018f22ce5 Pull complete                                                                                                                                                   23.6s
   ⠿ 251f062c8a60 Pull complete                                                                                                                                                   23.8s
   ⠿ 7e8ebedae87f Pull complete                                                                                                                                                   24.0s
   ⠿ 2239226cd43b Pull complete                                                                                                                                                   24.1s
[+] Running 2/2
 ⠿ Network IOTstack_Net  Created                                                                                                                                                   0.4s
 ⠿ Container postgres    Started                                                                                                                                                   1.5s

pi@sec-dev:~/IOTstack$ DPS
NAMES      CREATED         STATUS
postgres   8 seconds ago   Up 6 seconds

pi@sec-dev:~/IOTstack$ docker logs postgres
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... Etc/UTC
creating configuration files ... ok
running bootstrap script ... ok
performing post-bootstrap initialization ... ok
syncing data to disk ... ok


Success. You can now start the database server using:
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2021-12-15 11:06:35.333 UTC [49] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 32-bit
2021-12-15 11:06:35.336 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-12-15 11:06:35.347 UTC [50] LOG:  database system was shut down at 2021-12-15 11:06:34 UTC
2021-12-15 11:06:35.364 UTC [49] LOG:  database system is ready to accept connections
 done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

2021-12-15 11:06:35.902 UTC [49] LOG:  received fast shutdown request
waiting for server to shut down....2021-12-15 11:06:35.904 UTC [49] LOG:  aborting any active transactions
2021-12-15 11:06:35.909 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
2021-12-15 11:06:35.910 UTC [51] LOG:  shutting down
2021-12-15 11:06:35.942 UTC [49] LOG:  database system is shut down
 done
server stopped

PostgreSQL init process complete; ready for start up.

2021-12-15 11:06:36.075 UTC [1] LOG:  starting PostgreSQL 14.1 (Debian 14.1-1.pgdg110+1) on arm-unknown-linux-gnueabihf, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 32-bit
2021-12-15 11:06:36.076 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2021-12-15 11:06:36.076 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2021-12-15 11:06:36.081 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2021-12-15 11:06:36.091 UTC [63] LOG:  database system was shut down at 2021-12-15 11:06:35 UTC
2021-12-15 11:06:36.108 UTC [1] LOG:  database system is ready to accept connections
pi@sec-dev:~/IOTstack$ 
```

**Comment by Paraphraser** [comment]
The other thing it might be worth thinking about is how environment variables are used. For passwords, they tend to be "one time only". So, let's say you had:

```
POSTGRES_PASSWORD=%randomPassword%
```

at some point. If Postgres got going far enough to initialise everything, that will be the password. If you come along and change the right hand side later, it doesn't cause a change in the database. The database will continue to believe `%randomPassword%` is the root password. All sorts of things behave this way, not just databases.

It might be that all you need to do is:

1. Stop Postgres from running.
2. `sudo rm -rf ~/IOTstack/volumes/postgres`
3. Start Postgres again.

**Comment by hughk** [comment]
First, thanks for getting back to me so quickly. The issue I believe is that I attempted to use the options alongside the Postgres entry on the new menu to set the password rather than the default  (I have an allergy to default passwords). On a new installation with a fresh git clone as you suggest, the problem repeats when I get to step 4 in the list that you made in your first answer.

`Traceback (most recent call last):
  File "/home/pi/IOTstack/./scripts/menu_main.py", line 456, in <module>
    runSelection(currentMenuItemIndex)
  File "/home/pi/IOTstack/./scripts/menu_main.py", line 411, in runSelection
    mainMenuList[selection][1]()
  File "/home/pi/IOTstack/./scripts/menu_main.py", line 110, in buildStack
    exec(code, execGlobals, execLocals)
  File "./scripts/buildstack_menu.py", line 635, in <module>
    main()
  File "./scripts/buildstack_menu.py", line 604, in main
    executeServiceOptions()
  File "./scripts/buildstack_menu.py", line 519, in executeServiceOptions
    exec(code, execGlobals, execLocals)
  File "./.templates//postgres/build.py", line 397, in <module>
    main()
  File "./.templates//postgres/build.py", line 387, in main
    eval(toRun)()
  File "./.templates//postgres/build.py", line 252, in runOptionsMenu
    menuEntryPoint()
  File "./.templates//postgres/build.py", line 360, in menuEntryPoint
    runSelection(currentMenuItemIndex)
  File "./.templates//postgres/build.py", line 317, in runSelection
    postgresDbBuildOptions[selection][1]()
  File "./.templates//postgres/build.py", line 218, in setPasswordOptions
    with open(passwordOptionsMenuFilePath, "rb") as pythonDynamicImportFile:
`
If I retry using the default or an environment variable it works perfectly.
