### ISSUE TITLE
Error selecting webthings_gateway in the menu

### ISSUE THREAD

**Issue by ukkopahis** [SensorsIot/IOTstack#583]
When pressing space to select:
![image](https://user-images.githubusercontent.com/95980324/175800004-567372f5-c55d-447f-b1ee-cc99f351d943.png)

**Comment by ukkopahis** [comment]
And after CTRL-c
``` py2tb
Traceback (most recent call last):
  File "./scripts/buildstack_menu.py", line 359, in loadService
    dockerComposeServicesYaml[serviceName] = yaml.load(yamlServiceFile)[serviceName]
  File "/home/blomkim/.local/lib/python3.9/site-packages/ruamel/yaml/comments.py", line 927, in __getitem__
    return ordereddict.__getitem__(self, key)
KeyError: 'webthings_gateway'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/blomkim/src/IOTstack/./scripts/menu_main.py", line 456, in <module>
    runSelection(currentMenuItemIndex)
  File "/home/blomkim/src/IOTstack/./scripts/menu_main.py", line 411, in runSelection
    mainMenuList[selection][1]()
  File "/home/blomkim/src/IOTstack/./scripts/menu_main.py", line 110, in buildStack
    exec(code, execGlobals, execLocals)
  File "./scripts/buildstack_menu.py", line 635, in <module>
    main()
  File "./scripts/buildstack_menu.py", line 616, in main
    checkMenuItem(selection) # Update checked list
  File "./scripts/buildstack_menu.py", line 538, in checkMenuItem
    loadService(menu[selection][0])
  File "./scripts/buildstack_menu.py", line 373, in loadService
    input("Press Enter to exit...")
KeyboardInterrupt
```
